version: '3'
services:
  mariadb:
    build:
      context: ./mariadb
    volumes:
      - maria-data:/var/lib/mysql
    ports:
      - 3306:3306

  solr-vivo:
    build:
      context: ./solr-vivo
    ports:
      - 8984:8983

#  solr-discovery:
#    build:
#      context: ./solr-discovery
#    ports:
#     - 8983:8983

  vivo:
    build:
      context: ./vivo
    volumes:
      - ./example-config:/usr/local/vivo/home/config
      - tdb-model-data:/usr/local/vivo/home/tdbModels
    depends_on:
      - mariadb
      - solr-vivo

  # discovery-api:
  #   build:
  #     context: ./discovery
  #   ports:
  #     - 9000:9000
  #   environment:
  #     - GMAIL_USERNAME=${GMAIL_USERNAME}
  #     - GMAIL_PASSWORD=${GMAIL_PASSWORD}
  #   # command: sh -c 'tail -f /dev/null'

  # discovery-client:
  #   image: scholars-angular
  #   environment:
  #     - HOST=localhost
  #     - PORT=4200
  #     - BASE_HREF=/
  #     - SERVICE_URL=http://localhost:9000
  #     - EMBED_URL=http://localhost:4201
  #     - VIVO_URL=http://localhost:8080/vivo
  #   ports:
  #     - 4200:4200

  proxy:
    build:
      context: ./proxy
    ports:
      - 8080:8080
    environment:
      - APP_URL=http://localhost:8080
      - CAS_URL=https://ssodev.ucdavis.edu/cas
      - CAS_AGENT_DOMAIN=ucdavis.edu
    # volumes:
    #   - ./proxy/index.js:/proxy/index.js
    #   - ./proxy/cas.js:/proxy/cas.js
    # command: bash -c 'tail -f /dev/null'


volumes:
  solr-data:
  maria-data:
  tdb-model-data:
